### ISSUE TITLE
How to work with bytearray?

### ISSUE THREAD

**Issue by pompushko** [SeaHOH/jsengine#2]
Hello, could you please help me with bytearrays?

```
byte_array = bytearray.fromhex("93 14 2C 08")
array = ctx1.call("calculateKey", byte_array)
```

but i got
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
```

Thank you.

**Comment by SeaHOH** [comment]
Why bytearrays? JavaScript has no this type, how does it work in JavaScript?

Here use `string` (`ctx.eval`) and supported types by `json` (`ctx.call`) to pass arguments to the backend engines.

**Comment by pompushko** [comment]
> Why bytearrays? JavaScript has no this type, how does it work in JavaScript?
> 
> Here use `string` (`ctx.eval`) and supported types by `json` (`ctx.call`) to pass arguments to the backend engines.

Thank you for responce. Actually, I am not good in JS :)

Here is a part code of JS script:
```
function calculateKey(seed) {
    if (seed.length < 4) {
        throw "seed length must be at least 4";
    }

    var hiSeed = ((seed[0] << 8) + seed[1]) & 0xFFFFFFFF;
    var loSeed = ((seed[2] << 8) + seed[3]) & 0xFFFFFFFF;
```


and I still cant understand how to pass my byte arrar to that function :(

**Comment by SeaHOH** [comment]
Looks like the `seed` is a `array` (`list` in Python) object, and its members' type is `Number` (`int` in Python). So, the code may like this:

```py
byte_array = list(bytes.fromhex("93 14 2C 08"))  # both bytes and bytearray are OK
array = ctx1.call("calculateKey", byte_array)
```
